In [79]:
# 1. Importing file sharks and making a copy:

import pandas as pd
import os

os.chdir('C:/Users/Kasia/TEST/806_Repo/Labs/module_1/Pipelines-Project/204_47432_compressed_attacks')
sharks=pd.read_csv("attacks.csv", encoding='latin-1')
data = sharks.copy()

In [80]:
# 2. Examining data:
data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [81]:
data.shape

(25723, 24)

In [82]:
data.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [83]:
#checking what unique values I have in each column to get more idea of what I have in my data:
data["Injury"].unique()

array(['No injury to occupant, outrigger canoe and paddle damaged',
       'Minor injury to left thigh',
       'Injury to left lower leg from surfboard skeg', ...,
       'FATAL, leg stripped of flesh  ',
       'FATAL, knocked overboard by tail of shark & carried off by shark ',
       'FATAL. "Shark bit him in half, carrying away the lower extremities" '],
      dtype=object)

In [84]:
"""
3. After checking what my data looks like, I am defining my purpose of cleaning the data:

Travel agency is studying about best locations to organize water sports escapades.
They are asking me:
- which countries are to avoid when it comes to shark attacks danger;
- the risk that the shark attack will be fatal;
- if there is any seasonality in shark attacks, so they could avoid certain months.

So to my study, the most important columns are:
Country, Year - these cannot be nan
Fatal, Date - these, even if nan, I keep, bc they still give me info that there was an attack in specyfic country
"""

'\n3. After checking what my data looks like, I am defining my purpose of cleaning the data:\n\nTravel agency is studying about best locations to organize water sports escapades.\nThey are asking me:\n- which countries are to avoid when it comes to shark attacks danger;\n- the risk that the shark attack will be fatal;\n- if there is any seasonality in shark attacks, so they could avoid certain months.\n\nSo to my study, the most important columns are:\nCountry, Year - these cannot be nan\nFatal, Date - these, even if nan, I keep, bc they still give me info that there was an attack in specyfic country\n'

In [85]:
# 4. I decided to drop columns at the end of the pricess, bc even unnecessary columns I might need to clean necessary columns.
# ( I have learnt it hard way ;)

In [86]:
# 5. I will check if there are duplicated rows:

#data.duplicated(subset=["Date","Name","Location", "Injury","Time"])
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
25718     True
25719     True
25720     True
25721     True
25722    False
Length: 25723, dtype: bool

In [87]:
# 6. Apparently there are exact duplicates, I will get rid of them:
data = data.drop_duplicates()
data.shape

(6312, 24)

In [88]:
# 7. If I understand well, there were 21k rows duplicated??? I hope I understand well...

In [89]:
# 8. Checking my important columns for unique values
data["Year"].unique()

array([2018., 2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011.,
       2010., 2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002.,
       2001., 2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994.,
       1993., 1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986.,
       1985., 1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976.,
       1975., 1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966.,
       1965., 1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957.,
       1956., 1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948.,
       1848., 1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940.,
       1939., 1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931.,
       1930., 1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922.,
       1921., 1920., 1919., 1918., 1917., 1916., 1915., 1914., 1913.,
       1912., 1911., 1910., 1909., 1908., 1907., 1906., 1905., 1904.,
       1903., 1902., 1901., 1900., 1899., 1898., 1897., 1896., 1895.,
       1894., 1893., 1892., 1891., 1890., 1889., 1888., 1887., 1886.,
       1885., 1884., 1883., 1882., 1881., 1880., 1879., 1878., 1877.,
       1876., 1875., 1874., 1873., 1872., 1871., 1870., 1869., 1868.,
       1867., 1866., 1865., 1864., 1863., 1862., 1861., 1860., 1859.,
       1858., 1857., 1856., 1855., 1853., 1852., 1851., 1850., 1849.,
       1847., 1846., 1845., 1844., 1842., 1841., 1840., 1839., 1837.,
       1836., 1835., 1834., 1832., 1831., 1830., 1829., 1828., 1827.,
       1826., 1825., 1823., 1822., 1819., 1818., 1817., 1816., 1815.,
       1812., 1811., 1810., 1808., 1807., 1805., 1804., 1803., 1802.,
       1801., 1800., 1797., 1792., 1791., 1788., 1787., 1786., 1785.,
       1784., 1783., 1780., 1779., 1776., 1771., 1767., 1764., 1758.,
       1753., 1751., 1749., 1755., 1748., 1742., 1738., 1733., 1723.,
       1721., 1703., 1700., 1642., 1638., 1637., 1617., 1595., 1580.,
       1555., 1554., 1543.,  500.,   77.,    5.,    0.])

In [90]:
# 9. Will start with Year - it goes back to 1543:
indexNames = data[data['Year'] < 2000].index
data.drop(indexNames , inplace=True)
data["Year"].unique()

array([2018., 2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011.,
       2010., 2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002.,
       2001., 2000.])

In [91]:
data.shape

(2090, 24)

In [92]:
# 10. Year column is essential to me (the migration of sharks every 20 years), so I will drop nans:
data.dropna(subset = ["Year"], inplace=True)
data["Year"].unique()

array([2018., 2017., 2016., 2015., 2014., 2013., 2012., 2011., 2010.,
       2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002., 2001.,
       2000.])

In [93]:
data.shape

(2078, 24)

In [94]:
# 11. Checking Fatality column:
data["Fatal (Y/N)"].unique()

array(['N', 'Y', nan, 'M', 'UNKNOWN', '2017'], dtype=object)

In [95]:
# 12. Will clean values:
data["Fatal (Y/N)"] = data["Fatal (Y/N)"].str.replace('M', 'N')
data.["Fatal (Y/N)"].unique()

SyntaxError: invalid syntax (<ipython-input-95-0dbea2ab1270>, line 3)

In [96]:
# 13. I constate that having spaces in col name is not a good thing, will rename this column first:
data = data.rename(columns={'Fatal (Y/N)':'Fatality'})
# 14. and clean the M/N:
data["Fatality"] = data["Fatality"].str.replace('M', 'N')
data.Fatality.unique()

array(['N', 'Y', nan, 'UNKNOWN', '2017'], dtype=object)

In [97]:
# 15. 
data.Fatality.value_counts()

N          1739
Y           175
UNKNOWN       2
2017          1
Name: Fatality, dtype: int64

In [98]:
# 16. looks good, 3 values that is tempting to drop/leave them, but let s see if possible to correct them:
# question in my head, shall i drop these 3 rows of nan or keep the for the sake of other info in the row?
#I will keep them for now
data.loc[data['Fatality'] == "2017"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
786,2012.06.10,10-Jun-2012,2012.0,Provoked,ITALY,Sardinia,Muravera,Attempting to rescue an injured & beached shark,Giorgio Zara,M,...,"Blue shark, 2.5m","D. Puddo, 6/11/2012",2012.06.10-Zara.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.06.10,2012.06.10,5517.0,NaN,NaN

In [99]:
# 16a
data.loc[data['Fatality'] == "UNKNOWN"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
624,2013.09.08,08-Sep-2013,2013.0,Unprovoked,USA,South Carolina,"St. Helena Island, Beaufort County",NaN,female,F,...,NaN,"WIS-TV, 9/9/2013",2013.09.08-St-Helena.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.09.08,2013.09.08,5679.0,NaN,NaN
1270,2008.04.20.a,20-Apr-2008,2008.0,Unprovoked,AUSTRALIA,New South Wales,Crescent Head,NaN,Jamie Adlington,M,...,"Tiger shark, 2.3m","T. Peake, GSAF",2008.04.20.a-Adlington.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.04.20.a,2008.04.20.a,5033.0,NaN,NaN

In [100]:
# 17. seems like 2017 was not fatal, lets correct it:
data["Fatality"] = data["Fatality"].str.replace('2017', 'N')
data['Fatality'] = data['Fatality'].fillna("UNKNOWN")
data.Fatality.unique()

array(['N', 'Y', 'UNKNOWN'], dtype=object)

In [101]:
# 17a
# ok, looks good, but it wasnt piece of cake, been struggling with:
#NameError: name 'nan' is not defined, imported numby but it didnt help, then was this:
#TypeError: repl must be a string or callable
# grrrrr, I will change my nan to UNKNOWN instead:
#data['Fatality'] = data['Fatality'].fillna("UNKNOWN")
#data["Fatality"] = data["Fatality"].str.replace('','UNKNOWN')
#data.Fatality.unique()
#array(['UNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNNUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWN',
 #      'UNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNYUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWN',
  #     'UNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNUUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNNUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNKUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNNUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNOUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNWUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWNNUNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWN',
   #    'UNKNOWNUUNKNOWNNUNKNOWNKUNKNOWNNUNKNOWNOUNKNOWNWUNKNOWNNUNKNOWN'],
    #  dtype=object)

In [102]:
# 18. I will now work on Country column:
data["Country"].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'FIJI', 'PUERTO RICO',
       'ITALY', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA'], dtype=object)

In [103]:
# 19. It seems pretty clean to me, I will only 
# - change nans na UNMKNOWN
# - merge FIJI with Fiji
# - merge England with United Kingdom (eventhough missing some information)
data['Country'].fillna('UNKNOWN', inplace=True)
data['Country'] = data['Country'].str.strip().str.upper()
data["Country"] = data["Country"].str.replace('ENGLAND', 'NUNITED KINGDOM')
data["Country"].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'NUNITED KINGDOM',
       'SOUTH AFRICA', 'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS',
       'NEW CALEDONIA', 'ECUADOR', 'MALAYSIA', 'LIBYA', 'UNKNOWN', 'CUBA',
       'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS',
       'JAPAN', 'EGYPT', 'ST HELENA, BRITISH OVERSEAS TERRITORY',
       'COMOROS', 'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'FIJI', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO', 'ITALY',
       'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'SIERRA LEONE', 'ST. MAARTIN',
       'GRAND CAYMAN', 'LIBERIA', 'VANUATU', 'HONDURAS', 'VENEZUELA',
       'SRI LANKA', 'URUGUAY', 'INDIA', 'MICRONESIA', 'CARIBBEAN SEA',
       'OKINAWA', 'TANZANIA'], dtype=object)

In [104]:
# 20. I will check how many nans we have and if we can find the Country by its Area or Location column.
data.loc[data['Country'] == "UNKNOWN"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
62,2017.11.13.R,Reported 13-Nov-2017,2017.0,Unprovoked,UNKNOWN,NaN,NaN,Surfing,Timur Yunusov,M,...,NaN,Instagram,2017.11.13.R-Timur.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.11.13.R,2017.11.13.R,6241.0,NaN,NaN
525,2014.08.00,Aug-2014,2014.0,Invalid,UNKNOWN,NaN,NaN,Sea disaster,Cuban refugees,M,...,Shark involvement not confirmed,"Associated Press, 11/27/2014",2014.08.00-Cuban-refugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.08.00,2014.08.00,5778.0,NaN,NaN

In [105]:
# 21.We can drop these 2 rows:
indexNames = data[data['Country'] == "UNKNOWN"].index
data.drop(indexNames , inplace=True)
data["Country"].unique()

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'NUNITED KINGDOM',
       'SOUTH AFRICA', 'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS',
       'NEW CALEDONIA', 'ECUADOR', 'MALAYSIA', 'LIBYA', 'CUBA',
       'MAURITIUS', 'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS',
       'JAPAN', 'EGYPT', 'ST HELENA, BRITISH OVERSEAS TERRITORY',
       'COMOROS', 'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'FIJI', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'PUERTO RICO', 'ITALY',
       'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'SIERRA LEONE', 'ST. MAARTIN',
       'GRAND CAYMAN', 'LIBERIA', 'VANUATU', 'HONDURAS', 'VENEZUELA',
       'SRI LANKA', 'URUGUAY', 'INDIA', 'MICRONESIA', 'CARIBBEAN SEA',
       'OKINAWA', 'TANZANIA'], dtype=object)

In [106]:
# 22. not sure if there is a point to change data type (?)
display(data.Year.dtype)

dtype('float64')

In [107]:
# 23. Area seems OK
#data["Area"].unique()

In [108]:
# 24. geting statistical overview of our table, it brings nthn since we have non numerical data
summary=data.describe().T
summary.head()

,count,mean,std,min,25%,50%,75%,max
Year,2076.0,2009.407996,5.272681,2000.0,2005.00,2010.0,2014.00,2018.0
original order,2076.0,5262.871387,599.952129,4225.0,4743.75,5262.5,5782.25,6303.0

In [109]:
####### TRYING DIFFERENT THINGS

data1 = data.copy()

In [110]:
#import datetime
#data1['year'] = pd.DatetimeIndex(data1['Year']).year
#data1.head(50)

In [50]:
data1.shape

(2076, 24)

In [ ]:
def clean_colnames(df):
    '''Clean columns names when passing a pandas dataframe: params (df - dataframe)'''
    col_clean = []
    for col in df.columns:
        col = col.strip().upper()
        col_clean.append(col)
        
    df.columns = col_clean
    return df.columns

clean_colnames(data1)

In [ ]:
# 25. I will now try to extract months from Date column:
#data1.sample(50)
#data["Date"].value_counts()
# I notice that most (but not all) dates are in format dd-Month-yyyy, I will try to unify cells to one date format:

In [ ]:
# DOESN'T WORK:
#data1['Date'] = pd.to_datetime(data1['Date'])
#data1["Date"].dt.strftime("%d/%b/%y")

In [ ]:
# DOESN'T WORK:
#import numpy as np
#import datetime
#data1['Date'] = pd.to_datetime(data1['Date'])

In [ ]:
# DOESN'T WORK:
"""
data2 = data1.copy()
for row in data1['Date']:
    if data1.Date.str.startswith('Reported'):
            data2 = data1["Date"].str[9,:]

data2['Date'].value_counts()"""

In [ ]:
# DOESN'T WORK:
"""
data2 = data1.copy()
lista2 =[]
for row in data1['Date']:
    re_obj = re.sub(r'Reported ', '', row)
    lista2.append(re_obj)
data2['DateCorrected'] = lista2
data2['DateCorrected'].value_counts()
data2.head()"""

In [111]:
# WORKS! :)
# 1. extracting "-aaa-" from strings in Date
# 2. cleaning "-"
import re
import numpy as np
months_lst = []
for row in data1['Date']:
    #re_obj = ''.join(re.findall('[^\d]',text)) #checking for letters (non numeric characters)
    #re_obj = ''.join(re.findall('[A-Za-z]{4}\-',row)).lower() #searching for months written differently than -aaa-
    re_obj = ''.join(re.findall('\-[A-Za-z]{3}\-',row)).lower()
    re_obj = re.sub('\-','',re_obj)
        
        
    #if re_obj == '':
        #re_obj = np.nan

    months_lst.append(re_obj)
# adding a column Month:
data1['Month'] = months_lst

data1["Month"].value_counts()

jul    238
sep    222
jun    207
aug    192
apr    188
oct    177
may    157
mar    147
jan    138
dec    121
nov    119
feb    113
        57
Name: Month, dtype: int64

In [52]:
# I notice that findall didnt fid a match with 57 rows, I will check them:

In [112]:
data1.loc[data1['Month'] == ""]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Month
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,"Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN,
86,2017.09.14,Sep-2017,2017.0,Boating,AUSTRALIA,Westerm Australia,Esperance,Fishing,NaN,NaN,...,"B. Myatt, GSAF",2017.09.14-EsperanceBoats.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.09.14,2017.09.14,6217.0,NaN,NaN,
131,2017.06.05,2017.06.05,2017.0,Unprovoked,FRENCH POLYNESIA,Marquesas,"Atuona Bay, Hiva Oa Island",Surfing,male,M,...,"Tahiti Infos, 6/6/2017",2017.06.05-FrenchPolynesia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.05,2017.06.05,6172.0,NaN,NaN,
226,2016.09.00,Sep-2016,2016.0,Invalid,MEXICO,NaN,Guadalupe Island,Cage Diving,NaN,NaN,...,K. Yonker,2016.09.00-Breach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.00,2016.09.00,6077.0,NaN,NaN,
370,2015.09.00,Sep-2015,2015.0,Unprovoked,FIJI,NaN,NaN,Spearfishing,Viliame Lautiki,M,...,"Fiji Times, 2/8/2016",2015.09.00-Lautiki.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.09.00,2015.09.00,5933.0,NaN,NaN,
423,2015.05.20,20-May2015,2015.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Matthew Zaccaria,M,...,"WFTV, 5/20/2015",2015.05.20-Zaccaria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.05.20,2015.05.20,5880.0,NaN,NaN,
504,2014.09.00,Sep-2014,2014.0,Unprovoked,SPAIN,Catalonia,Salou,Playing with an air mattress,male,M,...,"A. Brenneka, Shark Attack Survivors",2014.09.00-Salou.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.09.00,2014.09.00,5799.0,NaN,NaN,
556,2014.05.13,13-May2014,2014.0,Unprovoked,USA,Florida,"Jacksonville Beach, Duval County",Wading,Mihaela Cosa,F,...,"M. Michaelson, Shark Research Institute",2014.05.13-Cosa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.05.13,2014.05.13,5747.0,NaN,NaN,
588,2014.00.00.b,2014,2014.0,Unprovoked,USA,Hawaii,NaN,Free diving / Photographing pilot whales,male,M,...,You Tube,2014.00.00.b-OceanicWhitetip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00.b,2014.00.00.b,5715.0,NaN,NaN,
589,2014.00.00,2014,2014.0,Boating,NEW ZEALAND,NaN,Stewart Island,Filming a documentary,Dinghy. Occupants: Jeff Kurr and Andy Casagrande,NaN,...,Discovery Channel,2014.00.00-Jeff-Andy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00,2014.00.00,5714.0,NaN,NaN,
598,2013.11.29,29-Nov2013,2013.0,Unprovoked,USA,Hawaii,"Keawekapu Beach, Kihei, Maui",Snorkeling,female,F,...,"L. Fujimoto, Maui News, 11/29/2013",2013.11.29-Maui.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.11.29,2013.11.29,5705.0,NaN,NaN,
719,2012.12.00,December 2012,2012.0,Unprovoked,NEW ZEALAND,South Island,"Sunday Cove, Fiordland",Scuba diving,Jenny Oliver,F,...,"Stuff.co.nz, 1/18/2013",2012.12.00-Oliver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.12.00,2012.12.00,5584.0,NaN,NaN,
767,2012.07.07.c,07-July-2012,2012.0,Unprovoked,BAHAMAS,Eleuthera,NaN,Spearfishing,Sean Connelly,M,...,S. Connelly,2012.07.07.c-Connelly.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.07.07.c,2012.07.07.c,5536.0,NaN,NaN,
802,2012.04.00,Apr-2013,2012.0,Unprovoked,USA,Florida,"Sanibel Island, Lee County",NaN,Dylan Hapworth,M,...,"Morning Sentinel, 4/20/2012",2012.04.00-Hapworth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.04.00,2012.04.00,5501.0,NaN,NaN,
955,2011.01.12.R,Reported 12-Jan 2011,2011.0,Unprovoked,MEXICO,Quintana Roo,Xcalak,Attempting to fix motor,Juan Miguel Infante Ramírez,M,...,Sharksurvivors.com,2011.01.12.R-Infante.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.01.12.R,2011.01.12.R,5348.0,NaN,NaN,
1024,2010.06.00,Jun-2010,2010.0,Unprovoked,USA,Florida,"Ponte Vedra Beach, St Johns County",Surfing,Matt Searcy,M,...,"Florida Times-Union, 7/28/2010",2010.06.00-Searcy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2010.06.00,2010.06.00,5279.0,NaN,NaN,
1036,2010.02.19,190Feb-2010,2010.0,Unprovoked,NEW ZEALAND,South Island,Tahunanui Beach,Swimming,Paul Baird,M,...,"Nelson Mail, 2/23/2010",2010.02.19-Baird.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2010.02.19,2010.02.19,5267.0,NaN,NaN,
1102,2009.07.31,31-July-2009,2009.0,Unprovoked,BAHAMAS,Abaco Islands,Spanish Cay,Spearfishing,Derek Mitchell,M,...,WPTV.com,2009.07.31-Mitchell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2009.07.31,2009.07.31,5201.0,NaN,NaN,
1177,2009.01.00,Jan-2009,2009.0,Unprovoked,CUBA,Guantanamo Province,Guantanamo,Spearfishing,John,NaN,...,"C. Johansson, GSAF",2009.01.00-Cuba.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2009.01.00,2009.01.00,5126.0,NaN,NaN,
1187,2008.12.00,Dec-2008,2008.0,Unprovoked,MOZAMBIQUE,Inhambane Province,Chidenguele,Spearfishing,Darryl Kriel,M,...,J. Little,2008.12.00-Kriel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.12.00,2008.12.00,5116.0,NaN,NaN,
1210,2008.09.00,Sep-2008,2008.0,Unprovoked,USA,Florida,Hutchinson Island,Surfing,Daryl Zbar,M,...,"C. Johannson, GSAF",2008.09.00-Zbar.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.09.00,2008.09.00,5093.0,NaN,NaN,
1239,2008.07.00,Late Jul-2008,2008.0,Boating,UNITED KINGDOM,Sussex,"Rock-a-Nore, Hastings",Rowing an inflatable dinghy,Occupants: Luke Jones & James Sequin,M,...,"Hastings Observer, 8/1/2008",2008.07.00-UK-dinghy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.07.00,2008.07.00,5064.0,NaN,NaN,
1292,2008.01.30,2008.01.30,2008.0,Provoked,JAPAN,Tokyo Bay,NaN,Diving,NaN,M,...,L Compagno,2008.01.30-GoblinShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.01.30,2008.01.30,5011.0,NaN,NaN,
1298,2008.00.00.b,Fall 2008,2008.0,Provoked,USA,Florida,"Off Fort Pierce, St. Lucie County",Fishing for snapper,Johnny Silva,M,...,Extremecoast.com/ 1/30/2009,2008.00.00.b-Silva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.00.00.b,2008.00.00.b,5005.0,NaN,NaN,
1299,2008.00.00.a,Summer-2008,2008.0,Unprovoked,MEXICO,Baja California,Playas de Tijuana,Surfing,Chase Edwards,M,...,"San Diego Reader, 1/7/2009",2008.00.00.a-Edwards.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.00.00.a,2008.00.00.a,5004.0,NaN,NaN,
1314,2007.11.00,November 2011,2007.0,Invalid,MEXICO,Baja California,Guadalupe Island,Shark diving,Patrick Walsh & Paul Damgaard,M,...,Today Show,2007.11.00-cage.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.11.00,2007.11.00,4989.0,NaN,NaN,
1366,2007.07.00,Jul-2007,2007.0,Invalid,SENEGAL,NaN,NaN,Murder,Alex Takyi,NaN,...,"Daily Guide, 8/20/2007",2007.07.00-Takyi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.07.00,2007.07.00,4937.0,NaN,NaN,
1385,2007.05.00,May-2007,2007.0,Provoked,BAHAMAS,Bimini Islands,NaN,Shark tagging,Sabrina Garcia,F,...,S. Garcia,2007.05.00-Garcia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.05.00,2007.05.00,4918.0,NaN,NaN,
1403,2007.02.00,Feb-2007,2007.0,Unprovoked,NEW CALEDONIA,Loyalty Islands,Ouvéa,Spearfishing,male,M,...,"Les Nouvelles Caledoniennes,",2007.02.00-Ouvea.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.02.00,2007.02.00,4900.0,NaN,NaN,
1425,2006.10.00.b,Oct-2006,2006.0,Unprovoked,BAHAMAS,New Providence Island,Nassau,Free diving / modeling,Renata Foucre,F,...,"J. Lambiet, Palm Beach Post, 10/22/2006",2006.10.00.b-Foucre.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.10.00.b,2006.10.00.b,4878.0,NaN,NaN,
1426,2006.10.00.a,Oct-2006,2006.0,Unprovoked,GULF OF ADEN,Between Somalia & Yemen,NaN,Murder,5 Ethiopian refugees,NaN,...,"United Nations High Commission for Refugees, 1...",2006.10.00.a-EthiopianRefugees.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.10.00.a,2006.10.00.a,4877.0,NaN,NaN,
1447,2006.08.00.b,Aug-2006,2006.0,Unprovoked,USA,North Carolina,"Masonboro Island, New Hanover County",Wading,Miriam Picklesimer,F,...,"C. Creswell, GSAF",2006.08.00.b-Picklesimer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.08.00.b,2006.08.00.b,4856.0,NaN,NaN,
1448,2006.08.00.a,Early Aug-2006,2006.0,Unprovoked,REUNION,NaN,Le Port,Spearfishing,male,M,...,"Clicanoo, 8/29/2006",2006.08.00.a-Reunion.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.08.00.a,2006.08.00.a,4855.0,NaN,NaN,
1465,2006.06.30.b,July 2006,2006.0,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Spearfishing,Bebe Hall,F,...,"Swimming World Magazine, 2 July 2006",2006.06.30.b-Bebe-Hall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.30.b,2006.06.30.b,4838.0,NaN,NaN,
1466,2006.06.30.a,July 2006,2006.0,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Spearfishing,Gary Hall,M,...,"Swimming World Magazine, 2 July 2006",2006.06.30.a-GaryHall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.30.a,2006.06.30.a,4837.0,NaN,NaN,
1626,2004.11.00,Nov-2004,2004.0,Unprovoked,NEW CALEDONIA,North Province,Koumac,Diving,Unknown,NaN,...,"Les Nouvelles Caledoniennes, 11/19/2004",2004.11.00-Koumac.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.11.00,2004.11.00,4677.0,NaN,NaN,
1648,2004.08.00,Aug-2004,2004.0,Boat,SOUTH AFRICA,KwaZulu-Natal,Park Rynie,Fishing,boat x 2,NaN,...,"J. Eager, scubaradio.com",2004.08.00-SAboats.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.08.00,2004.08.00,4655.0,NaN,NaN,
1709,2004.00.00,2004,2004.0,Unprovoked,AUSTRALIA,Western Australia,Redgate Beach,Surfing,Jack Carlsen,M,...,J. Carlsen,2004.00.00-Carlsen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.00.00,2004.00.00,4594.0,NaN,NaN,
1724,2003.11.00,Nov-2003,2003.0,Provoked,PANAMA,Pearl Islands,NaN,Spearfishing,Richard Hatch,M,...,"J. Eager, scubaradio.com",2003.11.00-RichardHatch.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.11.00,2003.11.00,4579.0,NaN,NaN,
1748,2003.09.00,Sep-2003,2003.0,Unprovoked,USA,Florida,"Boca Grande, Lee County",Wade-fishing,male,M,...,"B. Stout, News-Press, 9/24/2003",2003.09.00-wade-fisherman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.09.00,2003.09.00,4555.0,NaN,NaN,
1760,2003.07.00.c,Jul-2003,2003.0,Unprovoked,USA,Florida,"Fort Lauderdale, Broward County",Spearfishing,Mark Marks,M,...,M. Marks,2003.07.00.c-MarkMarks.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.07.00.c,2003.07.00.c,4543.0,NaN,NaN,
1761,2003.07.00.b,Late Jul-2003,2003.0,Unprovoked,FRENCH POLYNESIA,Society Islands,Moorea,Spearfishing,male,M,...,Noonsite.com,2003.07.00.b-Moorea.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.07.00.b,2003.07.00.b,4542.0,NaN,NaN,
1762,2003.07.00.a,Jul-2003,2003.0,Unprovoked,NEW ZEALAND,Cook Islands,Beveridge Reef,Snorkeling,Allen --,M,...,R. & J. Zorro; Noonsite.com,2003.07.00.a-BeveridgeReef.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.07.00.a,2003.07.00.a,4541.0,NaN,NaN,
1771,2003.06.00,Jun-2003,2003.0,Invalid,USA,South Carolina,"Pawleys Island, Georgetown County",Swimming,female,F,...,J. Eager,2003.06.00-PawleysIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.06.00,2003.06.00,4532.0,NaN,NaN,
1777,2003.05.00,May-2003,2003.0,Unprovoked,PHILIPPINES,Baatan,Limay,NaN,a resident of Barangay Luz,NaN,...,"D. Cervantes, Star",2003.05.00-Philippines.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2003.05.00,2003.05.00,4526.0,NaN,NaN,
1814,2002.11.00.a,Nov-2002,2002.0,Unprovoked,FRENCH POLYNESIA,Society Islands,Tetiaroa,"Fishing, standing in 2' of water",Scott Heywood,M,...,S. Heywood,2002.11.00-Heywood.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2002.11.00.a,2002.11.00.a,4489.0,NaN,NaN,
1938,2001.07.00,Jul-2001,2001.0,Unprovoked,USA,Georgia,"Jekyll Island, Glynn County",Floating face-down in knee-deep water,John Davis,M,...,"Atlanta Journal-Constitution, 9/5/2001; Florid...",2001.07.00-Davis.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.07.00,2001.07.00,4365.0,NaN,NaN,
1951,2001.05.00,May-2001,2001.0,Unprovoked,FIJI,Taveuni,NaN,"Spearfishing, carrying his catch",male,M,...,FijiTV,2001.05.00-Fiji.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.05.00,2001.05.00,4352.0,NaN,NaN,
1967,2001.04.02.b,02-Ap-2001,2001.0,Unprovoked,BRAZIL,Rio Grande de Norte,"Praia de Camapum, Macau",Batin,A.C.C.,F,...,M. Szpilman,2001.04.02.b-ACC.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.04.02.b,2001.04.02.b,4336.0,NaN,NaN,
1973,2001.03.00,Mar-2001,2001.0,Sea Disaster,CARIBBEAN SEA,NaN,Between St. Maarten & Anguilla,Sinking of the 40' Esperanza off St. Maartin w...,Unknown,NaN,...,"C. Johansson, GSAF",2001.03.00-Anguilla.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.03.00,2001.03.00,4330.0,NaN,NaN,
1987,2000.12.00,Dec-2000,2000.0,Unprovoked,NEW ZEALAND,Cook Islands,"Arorangi, Rarotonga",Surfing,female,F,...,"C. Tini, R.D. Weeks, GSAF",2000.12.00 - Arorangi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.12.00,2000.12.00,4316.0,NaN,NaN,
2017,2000.09.00.b,Early Sep-2000,2000.0,Unprovoked,TANZANIA,NaN,"Coco Beach, Dar-es-Salaam",Swimming,NaN,NaN,...,T. Thierry,2000.09.00-CocoBeach4.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.09.00.b,2000.09.00.b,4286.0,NaN,NaN,
2027,2000.08.00,Aug-2000,2000.0,Unprovoked,TANZANIA,NaN,"Coco Beach, Dar-es-Salaam",Swimming,NaN,NaN,...,T. Thierry,2000.08.00-NV-Tanzania.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.08.00,2000.08.00,4276.0,NaN,NaN,
2044,2000.07.00,Jul-2000,2000.0,Unprovoked,TANZANIA,NaN,"Coco Beach, Dar-es-Salaam",Swimming,NaN,NaN,...,T. Thierry,2000.07.00-NV-Tanzania.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.07.00,2000.07.00,4259.0,NaN,NaN,
2053,2000.06.00,Early Jun-2000,2000.0,Unprovoked,TANZANIA,NaN,"Coco Beach in Oyster Bay, 7 km north of Dar-es...",Swimming,male,M,...,T. Thierry,2000.06.00-CocoBeach1.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.06.00,2000.06.00,4250.0,NaN,NaN,
2070,2000.03.00,Mar-2000,2000.0,Unprovoked,USA,Louisiana,Midnight Lump (38 miles offshore),Spearfishing,Kurt Bickel,M,...,"R. Collier, GSAF",2000.03.00.a-Bickel.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.03.00,2000.03.00,4233.0,NaN,NaN,
2078,2000.00.00,2000,2000.0,Boat,USA,Florida,"Boca Grande, Lee County",Fishing for tarpon,"boat: occupant, Terry Winters",M,...,"B. Stout, News-Press, 7/2/2005",2000.00.00-BocaGrandeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.00.00,2000.00.00,4225.0,NaN,NaN,

In [54]:
# I notice that many of them can be easily corrected with another findall:

In [113]:
data2 = data1.copy()
months_lst = []
for row in data2['Date']:
    re_obj = ''.join(re.findall('[A-Za-z]{3}\-',row)).lower()
    re_obj = re.sub('\-','',re_obj)
        
        
    #if re_obj == '':
        #re_obj = np.nan

    months_lst.append(re_obj)

data2['Month'] = months_lst

data2["Month"].value_counts()

jul    245
sep    229
jun    210
aug    196
apr    189
oct    179
may    160
mar    149
jan    139
dec    123
nov    122
feb    115
        17
uly      2
mer      1
Name: Month, dtype: int64

In [56]:
# Great, I only have 17 unmatched rows and 3 matched, but need some cleaning
# let s have a lok at these 17 unmatched rows:

In [114]:
data2.loc[data2['Month'] == ""]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Month
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,"Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN,
131,2017.06.05,2017.06.05,2017.0,Unprovoked,FRENCH POLYNESIA,Marquesas,"Atuona Bay, Hiva Oa Island",Surfing,male,M,...,"Tahiti Infos, 6/6/2017",2017.06.05-FrenchPolynesia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.05,2017.06.05,6172.0,NaN,NaN,
423,2015.05.20,20-May2015,2015.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Matthew Zaccaria,M,...,"WFTV, 5/20/2015",2015.05.20-Zaccaria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.05.20,2015.05.20,5880.0,NaN,NaN,
556,2014.05.13,13-May2014,2014.0,Unprovoked,USA,Florida,"Jacksonville Beach, Duval County",Wading,Mihaela Cosa,F,...,"M. Michaelson, Shark Research Institute",2014.05.13-Cosa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.05.13,2014.05.13,5747.0,NaN,NaN,
588,2014.00.00.b,2014,2014.0,Unprovoked,USA,Hawaii,NaN,Free diving / Photographing pilot whales,male,M,...,You Tube,2014.00.00.b-OceanicWhitetip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00.b,2014.00.00.b,5715.0,NaN,NaN,
589,2014.00.00,2014,2014.0,Boating,NEW ZEALAND,NaN,Stewart Island,Filming a documentary,Dinghy. Occupants: Jeff Kurr and Andy Casagrande,NaN,...,Discovery Channel,2014.00.00-Jeff-Andy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00,2014.00.00,5714.0,NaN,NaN,
598,2013.11.29,29-Nov2013,2013.0,Unprovoked,USA,Hawaii,"Keawekapu Beach, Kihei, Maui",Snorkeling,female,F,...,"L. Fujimoto, Maui News, 11/29/2013",2013.11.29-Maui.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.11.29,2013.11.29,5705.0,NaN,NaN,
719,2012.12.00,December 2012,2012.0,Unprovoked,NEW ZEALAND,South Island,"Sunday Cove, Fiordland",Scuba diving,Jenny Oliver,F,...,"Stuff.co.nz, 1/18/2013",2012.12.00-Oliver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.12.00,2012.12.00,5584.0,NaN,NaN,
955,2011.01.12.R,Reported 12-Jan 2011,2011.0,Unprovoked,MEXICO,Quintana Roo,Xcalak,Attempting to fix motor,Juan Miguel Infante Ramírez,M,...,Sharksurvivors.com,2011.01.12.R-Infante.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.01.12.R,2011.01.12.R,5348.0,NaN,NaN,
1292,2008.01.30,2008.01.30,2008.0,Provoked,JAPAN,Tokyo Bay,NaN,Diving,NaN,M,...,L Compagno,2008.01.30-GoblinShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.01.30,2008.01.30,5011.0,NaN,NaN,
1298,2008.00.00.b,Fall 2008,2008.0,Provoked,USA,Florida,"Off Fort Pierce, St. Lucie County",Fishing for snapper,Johnny Silva,M,...,Extremecoast.com/ 1/30/2009,2008.00.00.b-Silva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.00.00.b,2008.00.00.b,5005.0,NaN,NaN,
1314,2007.11.00,November 2011,2007.0,Invalid,MEXICO,Baja California,Guadalupe Island,Shark diving,Patrick Walsh & Paul Damgaard,M,...,Today Show,2007.11.00-cage.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.11.00,2007.11.00,4989.0,NaN,NaN,
1465,2006.06.30.b,July 2006,2006.0,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Spearfishing,Bebe Hall,F,...,"Swimming World Magazine, 2 July 2006",2006.06.30.b-Bebe-Hall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.30.b,2006.06.30.b,4838.0,NaN,NaN,
1466,2006.06.30.a,July 2006,2006.0,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Spearfishing,Gary Hall,M,...,"Swimming World Magazine, 2 July 2006",2006.06.30.a-GaryHall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.30.a,2006.06.30.a,4837.0,NaN,NaN,
1709,2004.00.00,2004,2004.0,Unprovoked,AUSTRALIA,Western Australia,Redgate Beach,Surfing,Jack Carlsen,M,...,J. Carlsen,2004.00.00-Carlsen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.00.00,2004.00.00,4594.0,NaN,NaN,
1967,2001.04.02.b,02-Ap-2001,2001.0,Unprovoked,BRAZIL,Rio Grande de Norte,"Praia de Camapum, Macau",Batin,A.C.C.,F,...,M. Szpilman,2001.04.02.b-ACC.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.04.02.b,2001.04.02.b,4336.0,NaN,NaN,
2078,2000.00.00,2000,2000.0,Boat,USA,Florida,"Boca Grande, Lee County",Fishing for tarpon,"boat: occupant, Terry Winters",M,...,"B. Stout, News-Press, 7/2/2005",2000.00.00-BocaGrandeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.00.00,2000.00.00,4225.0,NaN,NaN,

In [58]:
# I wanted to clean with same method one more time, but it would overrate my previous condition
# so I tried to cut these 17 as a separate dataframe and do the cleaning on it,
# but there is an error to handle and it s for the matter of 4 rows, so decided to do it manually :)

In [115]:
data3 = data2.loc[data2['Month'] == ""]
data3.head(20)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Month
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,"Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN,
131,2017.06.05,2017.06.05,2017.0,Unprovoked,FRENCH POLYNESIA,Marquesas,"Atuona Bay, Hiva Oa Island",Surfing,male,M,...,"Tahiti Infos, 6/6/2017",2017.06.05-FrenchPolynesia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.05,2017.06.05,6172.0,NaN,NaN,
423,2015.05.20,20-May2015,2015.0,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Matthew Zaccaria,M,...,"WFTV, 5/20/2015",2015.05.20-Zaccaria.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2015.05.20,2015.05.20,5880.0,NaN,NaN,
556,2014.05.13,13-May2014,2014.0,Unprovoked,USA,Florida,"Jacksonville Beach, Duval County",Wading,Mihaela Cosa,F,...,"M. Michaelson, Shark Research Institute",2014.05.13-Cosa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.05.13,2014.05.13,5747.0,NaN,NaN,
588,2014.00.00.b,2014,2014.0,Unprovoked,USA,Hawaii,NaN,Free diving / Photographing pilot whales,male,M,...,You Tube,2014.00.00.b-OceanicWhitetip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00.b,2014.00.00.b,5715.0,NaN,NaN,
589,2014.00.00,2014,2014.0,Boating,NEW ZEALAND,NaN,Stewart Island,Filming a documentary,Dinghy. Occupants: Jeff Kurr and Andy Casagrande,NaN,...,Discovery Channel,2014.00.00-Jeff-Andy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00,2014.00.00,5714.0,NaN,NaN,
598,2013.11.29,29-Nov2013,2013.0,Unprovoked,USA,Hawaii,"Keawekapu Beach, Kihei, Maui",Snorkeling,female,F,...,"L. Fujimoto, Maui News, 11/29/2013",2013.11.29-Maui.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.11.29,2013.11.29,5705.0,NaN,NaN,
719,2012.12.00,December 2012,2012.0,Unprovoked,NEW ZEALAND,South Island,"Sunday Cove, Fiordland",Scuba diving,Jenny Oliver,F,...,"Stuff.co.nz, 1/18/2013",2012.12.00-Oliver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.12.00,2012.12.00,5584.0,NaN,NaN,
955,2011.01.12.R,Reported 12-Jan 2011,2011.0,Unprovoked,MEXICO,Quintana Roo,Xcalak,Attempting to fix motor,Juan Miguel Infante Ramírez,M,...,Sharksurvivors.com,2011.01.12.R-Infante.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.01.12.R,2011.01.12.R,5348.0,NaN,NaN,
1292,2008.01.30,2008.01.30,2008.0,Provoked,JAPAN,Tokyo Bay,NaN,Diving,NaN,M,...,L Compagno,2008.01.30-GoblinShark.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.01.30,2008.01.30,5011.0,NaN,NaN,
1298,2008.00.00.b,Fall 2008,2008.0,Provoked,USA,Florida,"Off Fort Pierce, St. Lucie County",Fishing for snapper,Johnny Silva,M,...,Extremecoast.com/ 1/30/2009,2008.00.00.b-Silva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.00.00.b,2008.00.00.b,5005.0,NaN,NaN,
1314,2007.11.00,November 2011,2007.0,Invalid,MEXICO,Baja California,Guadalupe Island,Shark diving,Patrick Walsh & Paul Damgaard,M,...,Today Show,2007.11.00-cage.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2007.11.00,2007.11.00,4989.0,NaN,NaN,
1465,2006.06.30.b,July 2006,2006.0,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Spearfishing,Bebe Hall,F,...,"Swimming World Magazine, 2 July 2006",2006.06.30.b-Bebe-Hall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.30.b,2006.06.30.b,4838.0,NaN,NaN,
1466,2006.06.30.a,July 2006,2006.0,Unprovoked,USA,Florida,"Florida Keys, Monroe County",Spearfishing,Gary Hall,M,...,"Swimming World Magazine, 2 July 2006",2006.06.30.a-GaryHall.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2006.06.30.a,2006.06.30.a,4837.0,NaN,NaN,
1709,2004.00.00,2004,2004.0,Unprovoked,AUSTRALIA,Western Australia,Redgate Beach,Surfing,Jack Carlsen,M,...,J. Carlsen,2004.00.00-Carlsen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.00.00,2004.00.00,4594.0,NaN,NaN,
1967,2001.04.02.b,02-Ap-2001,2001.0,Unprovoked,BRAZIL,Rio Grande de Norte,"Praia de Camapum, Macau",Batin,A.C.C.,F,...,M. Szpilman,2001.04.02.b-ACC.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2001.04.02.b,2001.04.02.b,4336.0,NaN,NaN,
2078,2000.00.00,2000,2000.0,Boat,USA,Florida,"Boca Grande, Lee County",Fishing for tarpon,"boat: occupant, Terry Winters",M,...,"B. Stout, News-Press, 7/2/2005",2000.00.00-BocaGrandeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.00.00,2000.00.00,4225.0,NaN,NaN,

In [ ]:
"""# another cleaning with findall:
months_lst = []
for row in data3['Date']:
    re_obj = ''.join(re.findall('\-[A-Za-z]{3}',row)).lower()
    re_obj = re.sub('\-','',re_obj)
        
        
    #if re_obj == '':
        #re_obj = np.nan

    months_lst.append(re_obj)

data3['Month'] = months_lst

data3["Month"].value_counts()


Looong error about using a copy of a piece of the data"""

In [119]:
data4 = data2.copy()
#data4["Date"] = data4["Date"].str.replace('May 2018', 'May')
#data4.loc[data4['Month'] == ""]

In [122]:
# I will manually change these 17 rows:
data4['Month'] = np.where(data4['Date'] == "May", "may", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "2017.06.05", "jun", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "20-May2015", "may", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "13-May2014", "may", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "29-Nov2013", "nov", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "December 2012", "dec", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "Reported 12-Jan 2011", "jan", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "2008.01.30", "jan", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "November 2011", "nov", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "July 2006", "jul", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "02-Ap-2001", "apr", data4['Month'])
#data4['Month'] = np.where(data4['Date'] == "uly", "jul", data4['Month'])



data4["Month"].value_counts()

jul    247
sep    229
jun    211
aug    196
apr    190
oct    179
may    162
mar    149
jan    141
nov    124
dec    124
feb    115
         6
uly      2
mer      1
Name: Month, dtype: int64

In [123]:
data4.loc[data4['Month'] == ""]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Month
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,"Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN,
588,2014.00.00.b,2014,2014.0,Unprovoked,USA,Hawaii,NaN,Free diving / Photographing pilot whales,male,M,...,You Tube,2014.00.00.b-OceanicWhitetip.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00.b,2014.00.00.b,5715.0,NaN,NaN,
589,2014.00.00,2014,2014.0,Boating,NEW ZEALAND,NaN,Stewart Island,Filming a documentary,Dinghy. Occupants: Jeff Kurr and Andy Casagrande,NaN,...,Discovery Channel,2014.00.00-Jeff-Andy.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2014.00.00,2014.00.00,5714.0,NaN,NaN,
1298,2008.00.00.b,Fall 2008,2008.0,Provoked,USA,Florida,"Off Fort Pierce, St. Lucie County",Fishing for snapper,Johnny Silva,M,...,Extremecoast.com/ 1/30/2009,2008.00.00.b-Silva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.00.00.b,2008.00.00.b,5005.0,NaN,NaN,
1709,2004.00.00,2004,2004.0,Unprovoked,AUSTRALIA,Western Australia,Redgate Beach,Surfing,Jack Carlsen,M,...,J. Carlsen,2004.00.00-Carlsen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2004.00.00,2004.00.00,4594.0,NaN,NaN,
2078,2000.00.00,2000,2000.0,Boat,USA,Florida,"Boca Grande, Lee County",Fishing for tarpon,"boat: occupant, Terry Winters",M,...,"B. Stout, News-Press, 7/2/2005",2000.00.00-BocaGrandeBoat.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2000.00.00,2000.00.00,4225.0,NaN,NaN,

In [124]:
# I will set those to "UNKNOWN"

data4['Month'] = np.where(data4['Date'] == "2014", "UNKNOWN", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "2014", "UNKNOWN", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "Fall 2008", "UNKNOWN", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "2004", "UNKNOWN", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "2000", "UNKNOWN", data4['Month'])

data4["Month"].value_counts()

jul        247
sep        229
jun        211
aug        196
apr        190
oct        179
may        162
mar        149
jan        141
nov        124
dec        124
feb        115
UNKNOWN      5
uly          2
mer          1
             1
Name: Month, dtype: int64

In [74]:
# I will check what is in "uly" row:
data4.loc[data4['Month'] == "uly"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Month
767,2012.07.07.c,07-July-2012,2012.0,Unprovoked,BAHAMAS,Eleuthera,NaN,Spearfishing,Sean Connelly,M,...,S. Connelly,2012.07.07.c-Connelly.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2012.07.07.c,2012.07.07.c,5536.0,NaN,NaN,uly
1102,2009.07.31,31-July-2009,2009.0,Unprovoked,BAHAMAS,Abaco Islands,Spanish Cay,Spearfishing,Derek Mitchell,M,...,WPTV.com,2009.07.31-Mitchell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2009.07.31,2009.07.31,5201.0,NaN,NaN,uly

In [75]:
#changing those to jul:
data4['Month'] = np.where(data4['Date'] == "07-July-2012", "jul", data4['Month'])
data4['Month'] = np.where(data4['Date'] == "31-July-2009", "jul", data4['Month'])

data4["Month"].value_counts()

jul        249
sep        229
jun        211
aug        196
apr        190
oct        179
may        163
mar        149
jan        141
nov        124
dec        124
feb        115
UNKNOWN      5
mer          1
Name: Month, dtype: int64

In [76]:
#checking the "mer" row:
data4.loc[data4['Month'] == "mer"]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Month
1299,2008.00.00.a,Summer-2008,2008.0,Unprovoked,MEXICO,Baja California,Playas de Tijuana,Surfing,Chase Edwards,M,...,"San Diego Reader, 1/7/2009",2008.00.00.a-Edwards.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.00.00.a,2008.00.00.a,5004.0,NaN,NaN,mer

In [78]:
#changing it to UNKNOWN:
data4['Month'] = np.where(data4['Date'] == "Summer-2008", "UNKNOWN", data4['Month'])
data4["Month"].value_counts()

jul        249
sep        229
jun        211
aug        196
apr        190
oct        179
may        163
mar        149
jan        141
nov        124
dec        124
feb        115
UNKNOWN      6
Name: Month, dtype: int64

In [125]:
# Now I will check the results of cleaning my dataframe:

data4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2076 entries, 0 to 2078
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             2076 non-null   object
 1   Date                    2076 non-null   object
 2   Year                    2076 non-null   float64
 3   Type                    2074 non-null   object
 4   Country                 2076 non-null   object
 5   Area                    1988 non-null   object
 6   Location                1991 non-null   object
 7   Activity                1985 non-null   object
 8   Name                    2043 non-null   object
 9   Sex                     1972 non-null   object
 10  Age                     1551 non-null   object
 11  Injury                  2074 non-null   object
 12  Fatality                2076 non-null   object
 13  Time                    1478 non-null   object
 14  Species                 1368 non-null   object
 15  Investigator or Source  2070 non-null   object
 16  pdf                     2076 non-null   object
 17  href formula            2076 non-null   object
 18  href                    2076 non-null   object
 19  Case Number.1           2076 non-null   object
 20  Case Number.2           2076 non-null   object
 21  original order          2076 non-null   float64
 22  Unnamed: 22             1 non-null      object
 23  Unnamed: 23             0 non-null      object
 24  Month                   2076 non-null   object
dtypes: float64(2), object(23)
memory usage: 421.7+ KB

In [128]:
# I will drop all unnecessary columns:
data4.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatality', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23', 'Month'],
      dtype='object')

In [129]:
data4.shape

(2076, 25)

In [130]:
cols_to_drop=['Case Number', 'Date', 'Type','Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Time','Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23']
data4 = data4.drop(cols_to_drop, axis=1)
data4.shape

(2076, 6)

In [140]:
data4.sample()

,Year,Month,Country,Area,Location,Fatality
1309,2007.0,nov,AUSTRALIA,New South Wales,"Wategos Beach, Byon Bay",N

In [139]:
# Looks ok, I will just change the column order to have Month next to Year:

# data4.insert(1, 'Month', data4.Month(1)) #doesn't work wit 1 as value(series), dont know why
data4 = data4[["Year", "Month", "Country","Area","Location", "Fatality"]]
data4.head()

,Year,Month,Country,Area,Location,Fatality
0,2018.0,jun,USA,California,"Oceanside, San Diego County",N
1,2018.0,jun,USA,Georgia,"St. Simon Island, Glynn County",N
2,2018.0,jun,USA,Hawaii,"Habush, Oahu",N
3,2018.0,jun,AUSTRALIA,New South Wales,Arrawarra Headland,N
4,2018.0,jun,MEXICO,Colima,La Ticla,N

In [145]:
# OK, I will export my cleaned data to csv:

os.chdir('C:/Users/Kasia/TEST/806_Repo/Labs/module_1/Pipelines-Project')
data4.to_csv("attacks_cleaned")